version: '3.4'

services:
  poc.blog.silohost:
    image: ${DOCKER_REGISTRY}pocblogsilohost
    build:
      context: .
      dockerfile: PoC.Blog.SiloHost/Dockerfile
    depends_on:
      - blogging.db.srv
      - orleans.db.srv

  blogging.db.srv:
    image: blogging.db.srv:latest
    build:
      context: DBDeploy
      dockerfile: blogging.db.srv.dockerfile
    environment: 
      - POSTGRES_PASSWORD=BloggingD!Bpasswor_D
    ports:
      - "5432:5432"

  orleans.db.srv:
    image: orleans.db.postgresql:latest
    build:
      context: DBDeploy
      dockerfile: orleans.db.srv.dockerfile
    environment: 
      - POSTGRES_PASSWORD=Orleans!Bpasswor_D
    ports:
      - "5433:5432"

  poc.blog.webclient:
    image: ${DOCKER_REGISTRY}pocblogwebclient
    build:
      context: .
      dockerfile: PoC.Blog.WebClient/Dockerfile
    depends_on:
      - orleans.db.srv
      - poc.blog.silohost
